### ISSUE TITLE
Filter on support threads has "tags" listed twice in dropdown

### ISSUE THREAD

**Issue by shaunmulligan** [product-os/jellyfish#1889]
## Expected Behavior
"tags" should only be listed once in the dropdown.

## Actual Behavior
When i click on the drop down to select what I want to filter on, i see 2 "tags" listed.

<img width="775" alt="Screen Shot 2019-05-08 at 15 20 53" src="https://user-images.githubusercontent.com/3915043/57378475-2244fd80-71a5-11e9-88d8-2d859ca1e35b.png">

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Browser: 
- OS: 
- Environment: 

## References

---

*Before submitting this issue, please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by kb2ma** [comment]
To audit support tickets, I would like to filter on tags. As it turns out, I must select the _second_ Tags entry in the dropdown to filter effectively. This bug is sooo error prone.

cc: @toochevere, @klutchell, @20k-ultra, @rmorillo24
