### ISSUE TITLE
Support for "Dark Mode"

### ISSUE THREAD

**Issue by dfunckt** [product-os/jellyfish#2462]
It would be nice if JF had a dark theme for low-light environment conditions :) Browsers slowly get "native" dark mode support too -- as in, they provide support for switching CSS based on the user's OS-wide preference. All that's left is *just* picking what the dark colours should be :) This is arguably super-low priority, but it would be great to have when one needs it given how much time we get to spend staring JF!

**Comment by LucianBuzzo** [comment]
A draft implementation is here https://github.com/product-os/jellyfish/pull/8678
