### ISSUE TITLE
Filter on Support General shows as JSON

### ISSUE THREAD

**Issue by shaunmulligan** [product-os/jellyfish#2550]
## Expected Behavior
Should only see the `inbox contains Paid` filter and it should filter to threads that match this.

## Actual Behavior
filter shows as `{"name":"inbox","operator":"contains","value":"Paid"}`, it also doesn't appear to filter correctly.

## Steps to Reproduce the Problem

1. Create a new filter
1.
1.

## Specifications

- Browser: https://whatsmybrowser.org/b/4A3Q5V3
- OS: macOS High Sierra 10.13.6
- Environment: production

## Screenshots

<img width="645" alt="Screen Shot 2019-09-27 at 17 38 11" src="https://user-images.githubusercontent.com/3915043/65869456-cdd03380-e37a-11e9-8ecc-a81af6d92374.png">

## References
https://www.flowdock.com/app/rulemotion/p-cyclops/threads/zaLQ6eWSxn6AhgOkeqnqVpj-lgA

---

*Before submitting this issue, please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by LucianBuzzo** [comment]
This is no longer an issue
