### ISSUE TITLE
Adding navigating to urls containing /# don't navigate the page

### ISSUE THREAD

**Issue by StefKors** [product-os/jellyfish#2986]
## Expected Behavior
expected the site to navigate to the correct page

## Actual Behavior
Site does not navigate and no redirects

## Steps to Reproduce the Problem

1. go to http://localhost:9000
1. add `/#/support-thread~4bfcba8-2030-45dd-a0ec-eb056bc192b2` behind the url
1. press enter

## Specifications

- Browser: 
   - https://whatsmybrowser.org/b/6JMC9UQ
   - https://whatsmybrowser.org/b/2HW7SJG
- OS: OSX 10.15
- Environment: devenv

**Comment by LucianBuzzo** [comment]
Closing this as this a url format we no longer use
