### ISSUE TITLE
backend: Index complex JSONB structures for full-text search

### ISSUE THREAD

**Issue by joshbwlng** [product-os/jellyfish#3824]
Need to find a smart way to only index useful values that exist within complex (object->array->object->string) JSONB structures such as `data->payload->attachments->name` in `message` cards.

One option is to use the `jsonb_to_tsvector()` function passing an option to only index values that are of type "string". While this is an easy approach, it has the downside of indexing possibly undesired values such as `message` `data->payload->attachments->url`:
```
jellyfish=# select jsonb_to_tsvector('english', cards.data#>'{payload,attachments}', '["string"]') from cards where slug='message-c09d92a0-e81b-461a-b643-30a28242df2b';
                                     jsonb_to_tsvector                                      
--------------------------------------------------------------------------------------------
 '/dir/file.jpg':3 'example.com':2 'example.com/dir/file.jpg':1 'file.jpg':7 'image/jpeg':5
(1 row)
```

**Comment by LucianBuzzo** [comment]
This is now resolved.
