### ISSUE TITLE
$$formula doesn't run card updates

### ISSUE THREAD

**Issue by StefKors** [product-os/jellyfish#4653]
## Expected Behavior
Just like when creating a card, $$formula should run on card updates

## Actual Behavior
Only when creating a card `$$formula` is run

## Steps to Reproduce the Problem

1. Create opportunity with a `recurringValue` and `nonRecurringValue` (don't forget link it to an account card so it shows up in the table lens)
1. See the sum of both values on `totalValue`
1. Update either `recurringValue` or `nonRecurringValue`
1. `totalValue` doesn't update

**Comment by LucianBuzzo** [comment]
This should be resolved
