### ISSUE TITLE
Triggered action create a whisper on behalf of the user who created the support thread

### ISSUE THREAD

**Issue by StefKors** [product-os/jellyfish#4725]
## Expected Behavior
Triggered action should create message on behalf of a jellyfish bot

## Actual Behavior
whisper is created on behalf of the (forum) user 

## Screenshots
<img width="779" alt="Screen Shot 2020-09-08 at 2 13 42 PM" src="https://user-images.githubusercontent.com/11800807/92475328-8171b280-f1dd-11ea-9a62-6d39351161fc.png">

## References
for example
- https://jel.ly.fish/64371e70-64c2-45c0-a593-41852eadc6cd
- https://jel.ly.fish/d0da7499-4450-4675-9d37-a7fbcaf6d9a6
- ttps://jel.ly.fish/c2625174-eb10-4161-b1b8-f773495ca3b1
-  https://jel.ly.fish/a835f9d6-74c0-4674-aced-53a935ef1343
- https://jel.ly.fish/653a59e7-90f5-4d3d-8d82-1470bde6dbc9

**Comment by LucianBuzzo** [comment]
We did a big refactor of the actor/permissions in triggered actions which I believe resolves this.
