### ISSUE TITLE
Timeline component requires scrolling to load new messages.

### ISSUE THREAD

**Issue by StefKors** [product-os/jellyfish#4772]
## Expected Behavior
When you toggle show/hide whispers on a timeline view, if the hide whispers list is less than the page size. It should load new messages.

## Actual Behavior
It is often required to scroll to new messages first.
Sometime you need to scroll only a couple pixes
Sometimes you need to scroll up and down first to "hit" the scroll limit again.

## Screenshots
![2020-05-11T12 41 17Z](https://user-images.githubusercontent.com/11800807/93113748-e768a900-f6b9-11ea-8cb9-e90696db0bbb.gif)

## References
https://jel.ly.fish/1d0c5ed7-c2a2-4a41-8560-9bfcc002bce8

**Comment by karaxuna** [comment]
Not an issue any more
