### ISSUE TITLE
Add hashtag-like command execution interface

### ISSUE THREAD

**Issue by joshbwlng** [product-os/jellyfish#6179]
## Expected Behavior
Should be able to naturally execute commands on contracts from within Jellyfish.

## Actual Behavior
Some users expect hashtags such as `#summary` to work in Jellyfish. Our position is that hashtags should be used as descriptors instead of function executors. This means that we do not plan on adding this for arch call items. We want to create a better command execution interface within Jellyfish in the future and don't want to reinforce bad habits in the meantime.

**Comment by LucianBuzzo** [comment]
Connects to https://github.com/product-os/jellyfish/issues/4807
