### ISSUE TITLE
No token provided, skipping analytics setup on PROD

### ISSUE THREAD

**Issue by Hades32** [product-os/jellyfish#7525]
I'm seeing `No token provided, skipping analytics setup` in my js console on prod, which seems to come from here:
https://github.com/product-os/jellyfish/blob/aa2656be592ea84c6c5df1175d0b818fe320f76e/apps/ui/lib/core/index.ts#L14-L16

If we don't use Mixpanel (whatever that is) we should remove all that

**Comment by Hades32** [comment]
Probably @joshbwlng knows what's that about

**Comment by joshbwlng** [comment]
@Hades32 I know we don't have a `analytics.mixpanel.token` path provided by `jellyfish-environment` so this makes me think it is a relic of the past that hasn't been dropped yet. I have also never seen a mixpanel token for JF anywhere and we obviously haven't needed this for a long time so I say we could safely drop this.

**Comment by joshbwlng** [comment]
Ah, it's here: https://github.com/product-os/jellyfish/blob/master/apps/ui/lib/environment.ts#L30
But no mixpanel token is set anywhere nor is it in the k8s configs (deploy-templates) so I do think it's safe to drop all mixpanel related code. I'll ask just in case.
