### ISSUE TITLE
[Sentry] JellyfishInvalidSchema: invalid key: profile

### ISSUE THREAD

**Issue by LucianBuzzo** [product-os/jellyfish#7953]
https://sentry.io/organizations/balena/issues/3020772857/?referrer=webhooks_plugin

*Generated by the ["productOS sentry->GitHub"](https://zapier.com/app/editor/112965344) zap on zapier.com*

**Comment by joshbwlng** [comment]
test

**Comment by joshbwlng** [comment]
another comment
